pipeline:
  build:
    image: node
    commands:
      - npm install
  lint:
    image: node
    commands:
      - npm run lint
  test:
    image: node
    commands:
      - npm test
  publish:
    image: node
    commands:
      - npx semantic-release
    environment:
      - GH_TOKEN=${SEMANTIC_RELEASE_GITHUB_TOKEN}
      - NPM_TOKEN=${SEMANTIC_RELEASE_NPM_TOKEN}

services:
  mongodb:
    image: mongo
  redis:
    image: redis