pipeline:
  build:
    image: node
    commands:
      - npm install
  lint:
    image: node
    commands:
      - npm run lint
  test:
    image: node
    commands:
      - npm test
    environment:
      - DRONE_CI=true
  publish:
    image: node
    commands:
      - printenv
      - npx semantic-release
    environment:
      - GH_TOKEN=${SR_GITHUB_TOKEN}
      - NPM_TOKEN=${SR_NPM_TOKEN}

services:
  mongodb:
    image: mongo
  redis:
    image: redis