pipeline:
  build:
    image: node
    commands:
      - npm install
  lint:
    image: node
    commands:
      - npm run lint
  test:
    image: node
    commands:
      - npm test
    environment:
      - DRONE_CI=true

services:
  mongodb:
    image: mongo
  redis:
    image: redis