pipeline:
  build:
    image: node
    commands:
      - npm install
  lint:
    image: node
    commands:
      - npm run lint
  test:
    image: node
    commands:
      - npm test
  publish:
    image: node
    commands:
      - git fetch --tags --quiet origin
      - npx semantic-release
    secrets: [ gh_token, npm_token ]
    when:
      branch: master

services:
  mongodb:
    image: mongo
  redis:
    image: redis